name: Whisper Notebook Test 

# Event: Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule: 
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:  #Enables manual triggering of the workflow

jobs:
  test-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10' 

      # Install a list of dependencies needed to run the notebooks
      - name: Install Dependencies
        run: |
          pip install nbconvert
          pip install jupyter
          
      - name: Execute Specific Notebook
        run: |
          jupyter nbconvert --execute docs/notebooks/FiveMinutesWithAI_Whisper.ipynb

